- name: Cherry Servers API module
  connection: local
  hosts: localhost
  tasks:
  - name: Deploy CherryServers server
    cherryservers_server:
      hostname: 'server3.turbo.com'
      plan_id: '161'
      project_id: '79813'
      image: 'Ubuntu 16.04 64bit'
      region: 'EU-East-1'
      new: true
      state: present
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'
